


class Lang:
    class en:
        wellcome        = "Hi!\nThis is Q&A bot of Researches Center for IMLPP!\nWrite your question to bot and admin will answer you soon.\n\nPowered by @Lazizjonov."
        be_admin        = "You became an admin in this Q&A chat."
        was_admin       = "You already was an admin in this Q&A chat."
        del_admin       = "Delete any admin?"
        no_hang         = "There is no hanging users!"
        choose_user     = "Choose one user from hanging users:"
        already_have    = "You already have conversation with user: "
        name            = "Name: "
        please_close    = "\nPlease close conversation with"
        no_con          = "You don't have any conversation to close!"
        closed_con      = "Your conversation was closed!"
        waiting         = "Currently, you are in a waiting list of users. Admin will answer you soon!"
        fix_that        = "Internal server error! Magicians will fix this soon!"
        mes_update      = "Your message was updated. Feel free to write."
        should_choose   = "You should choose user to talk."
        internal        = "Internal error no chat found!"
        choose_new      = "This user is not in the list of hanging users! Please choose new user."
        user            = "User: "
        user_id         = "ID: "
        date            = "Date: "
        con_start_err   = "Error in starting conversation. Please select another user."
        error           = "Error!"
        chosen          = "User is chosen!"
        had_con         = "Admin was having conversation with user - "
        send_wait       = "User is going to be sent to a waiting list!"
        cant_del_con    = "Couldn't delete conversation of deleting admin!"
        con_del         = "Conversation of admin was deleted!"
        prev_admin      = "Previous admin was deleted from conversation!"
        was_deleted     = "Sorry admin of this chat was deleted. Now you are in the list of waiting users."
        con_lost        = "Couldn't add user to hanging users list! Conversation is lost!"
        cant_del_adm    = "Couldn't delete admin please check if deleted!"
        adm_del         = "Admin is deleted!"
        done            = "Done!"
        close_con       = "✖️Close conversation✖️"
        ch_lang         = "🇬🇧Change language🇷🇺"
        choose_lan      = "Choose language: "
        same_lang       = "Your language is the same!"
        chooseUser      = "👥Users👥"
        allAdmins       = "👥Admins👥"
        closeCon        = "✖️Close chat✖️"
        exit            = "🚪Exit admin🚪"
        user_closed     = "User closed this chat!"
        admin_closed    = "Admin closed this chat!"
        please_rate     = "Please rate admin from 1 to 5"
        thanks          = "Thank you!"
        tell_report     = "Could you tell us the reason of your score?"
        tell_no         = "🙅‍♂️No, I don't want🙅‍♂️"
        feedback        = "🙏Thank you for your feedback!🙏"
        super_admin     = "You become an owner of this bot."
        delAdmin        = "🗑Delete admin🗑"
        chats           = "Chats: "
        rate            = "Rate: "
        spr             = "Super: "
        thisisyou       = "This is you!"
        admin_del_you   = "Owner is deleted you from admins!"
        hanging_user    = "There is a hanging user in bot!"
        hanging_many    = "There are %s hanging user in bot!"
        lang            = "Lang: "

    class ru(en):
        wellcome        = "Привет!\nЭто бот для вопросов и ответов Центра исследований ОРПТП!\nПишите ваш вопрос в чат и админ вам скоро ответит\n\nСделал @Lazizjonov."
        be_admin        = "Вы стали админом в этом чате вопросов и ответов."
        was_admin       = "Вы уже были админом в этом чате вопросов и ответов."
        del_admin       = "Удалить админа?"
        no_hang         = "Там нет зависающих пользователей!"
        choose_user     = "Выберите одного пользователя."
        already_have    = "У вас уже есть диалог с пользователем: "
        name            = "Имя: "
        please_close    = "\nПожалуйста, завершите диалог с"
        no_con          = "Нет никаких диалогов!"
        closed_con      = "Ваши диалоги были закрыты!"
        waiting         = "В настоящее время вы находитесь в списке ожидающих пользователей. Админ ответит вам в ближайшее время!"
        fix_that        = "Внутренняя ошибка сервера! Волшебники скоро это исправят!"
        mes_update      = "Ваше сообщение было обновлено. Не стесняйтесь писать."
        should_choose   = "Вы должны выбрать пользователя для диалога."
        internal        = "Внутренняя ошибка чат не найден!"
        choose_new      = "Этого пользователя нет в списке зависших пользователей! Пожалуйста, выберите нового пользователя."
        user            = "Пользователь: "
        user_id         = "ID: "
        date            = "Дата: "
        con_start_err   = "Ошибка при запуске диалога. Пожалуйста, выберите другого пользователя."
        error           = "Ошибка!"
        chosen          = "Пользователь выбран!"
        had_con         = "Админ разговаривал с пользователем - "
        send_wait       = "Пользователь будет отправлен в список ожидания!"
        cant_del_con    = "Не удалось удалить беседу данного админа!"
        con_del         = "Беседа админа была удалена!"
        prev_admin      = "Предыдущий админ был удален из разговора!"
        was_deleted     = "Извините, админ этого чата был удален. Теперь вы находитесь в списке ожидающих пользователей."
        con_lost        = "Не удалось добавить пользователя в список зависших пользователей! Диалог потерян!"
        cant_del_adm    = "Ошибка при удалении админа, пожалуйста, проверьте, удален ли он!"
        adm_del         = "Админ удален!"
        done            = "Сделано!"
        close_con       = "✖️Закрыть чать✖️"
        ch_lang         = "🇬🇧Сменить язык🇷🇺"
        choose_lan      = "Выберите язык: "
        same_lang       = "У вас тот-же язык!"
        chooseUser      = "👥Пользователи👥"
        allAdmins       = "👥Админы👥"
        closeCon        = "✖️Закрыть чат✖️"
        exit            = "🚪Разадминиться🚪"
        user_closed     = "Пользователь закрыл этот чат!"
        admin_closed    = "Админ закрыл этот чат!"
        please_rate     = "Пожалуйста, оцените админа от 1 до 5"
        thanks          = "Спасибо!"
        tell_report     = "Не могли бы вы рассказать нам о причине вашего балла?"
        tell_no         = "🙅‍♂️Нет, я не хочу🙅‍♂️"
        feedback        = "🙏Спасибо вам за ваш отзыв!🙏"
        super_admin     = "Вы становитесь владельцем этого бота."
        delAdmin        = "🗑Удалить админа🗑"
        chats           = "Чаты: "
        rate            = "Оценка: "
        spr             = "Владелец: "
        thisisyou       = "Это же вы!"
        admin_del_you   = "Владелец отстранил вас от админа!"
        hanging_user    = "В боте есть зависший пользователь!"
        hanging_many    = "В боте есть %s зависших пользователей!"
        lang            = "Язык: "

    class uz(en):
        wellcome        = "Salom!\nBu TBIChMU tadqiqotlari markazi uchun savol-javob bot!\nSavolingizni yozing va admin sizga tez orada javob beradi.\n\nDeveloped by @Lazizjonov."
        be_admin        = "Siz chat admini bo'ldingiz."
        was_admin       = "Siz oldindan chat admini edingiz"
        del_admin       = "Adminni o'chirish kerakmi?"
        no_hang         = "Hozircha foydalanuvchilar mavjud emas!"
        choose_user     = "Foydalanuvchilardan birini tanlang:"
        already_have    = "Sizda foydalanuvchi bilan suhbat mavjud: "
        name            = "Ismi: "
        please_close    = "\nIltimos suhbatni yoping! "
        no_con          = "Sizda yopiladigan suhbat yo'q!"
        closed_con      = "Siz suhbatni yopdingiz!"
        waiting         = "Hozircha siz kutish ro'yxatidasiz. Admin sizga tez orada javob beradi!"
        fix_that        = "Ichki server xatosi!"
        mes_update      = "Sizning xabaringiz qo'shildi. Yana xabarlar jo'natishingiz mumkin."
        should_choose   = "Siz suhbat qilish uchun foydalanuvchini tanlashingiz kerak."
        internal        = "Ichki xato suhbat topilmadi!"
        choose_new      = "Ushbu foydalanuvchi kutish ro'yxatida emas! Iltimos boshqa foydalanuvchini tanlang."
        user            = "Foydalanuvchi: "
        user_id         = "ID: "
        date            = "Sana: "
        con_start_err   = "Suhbat boshlashda xatolik. Boshqa foydalanuvchi tanlang."
        error           = "Xatolik!"
        chosen          = "Foydalanuvchi tanlandi!"
        had_con         = "Admin foydalanuvchi bilan suhbaq qilayotgan edi - "
        send_wait       = "Foydalanuvchi kutish ro'yxatiga o'tkaziladi!"
        cant_del_con    = "O'chirilayotgan Adminning suhbatini o'chirishda xatolik!"
        con_del         = "Admin suhbati o'chirildi!"
        prev_admin      = "Oldingi admin suhbat jarayonida o'chirilgan!"
        was_deleted     = "Uzur suhbat admini o'chirildi. Endi siz kutish ro'yxatiga o'tkazildingiz."
        con_lost        = "Foydalanuvchini kutish ro'yxatiga o'tkazishda xatolik! Suhbat yo'qotildi!"
        cant_del_adm    = "Adminni o'chirishda xatolik, Adminlar ro'yxatini tekshiring!"
        adm_del         = "Admin o'chirildi!"
        done            = "Bajarildi!"
        close_con       = "✖️Chatni yopish✖️"
        ch_lang         = "🇬🇧Tilni almashtirish🇷🇺"
        choose_lan      = "Tilni tanlang: "
        same_lang       = "Bu sizning tilingiz!"
        chooseUser      = "👥Foydalanuvchilar👥"
        allAdmins       = "👥Adminlar👥"
        closeCon        = "✖️Chatni yopish✖️"
        exit            = "🚪Admindan chiqish🚪"
        user_closed     = "Foydalanuvchi bu chatni yopdi!"
        admin_closed    = "Admin bu chatni yopdi!"
        please_rate     = "Iltimos, adminga 1 dan 5 gacha baho bering"
        thanks          = "Rahmat!"
        tell_report     = "Balingiz sababini bizga ayta olasizmi?"
        tell_no         = "🙅‍♂️Yo'q, istamayman🙅‍♂️"
        feedback        = "🙏Mulohazalaringiz uchun rahmat!🙏"
        super_admin     = "Siz ushbu botning egasiga aylandingiz."
        delAdmin        = "🗑Admini o'chirish🗑"
        chats           = "Chatlar: "
        rate            = "Baho: "
        spr             = "Bot egasi: "
        thisisyou       = "Bu siz!"
        admin_del_you   = "Bot egasi sizni admindan o'chirdi!"
        hanging_user    = "Bitta foydalanuvchi javob kutmoqda!"
        hanging_many    = "%s ta foydalanuvchilar javob kutishmoqda!"
        lang            = "Til: "

    class oz(en):
        wellcome        = "Салом! \nБу ТБИЧМУ тадқиқотлари маркази учун савол-жавоб бот!\nСаволингизни ёзинг ва админ сизга тез орада жавоб беради.\n\nDeveloped by @Lazizjonov."
        be_admin        = "Сиз чат админи бўлдингиз."
        was_admin       = "Сиз олдиндан чат админи эдингиз"
        del_admin       = "Aдминни ўчириш керакми?"
        no_hang         = "Ҳозирча фойдаланувчилар мавжуд эмас!"
        choose_user     = "Фойдаланувчилардан бирини танланг:"
        already_have    = "Сизда фойдаланувчи билан суҳбат мавжуд:"
        name            = " Исми: "
        please_close    = "\nИлтимос суҳбатни ёпинг "
        no_con          = "Сизда ёпиладиган суҳбат йўқ!"
        closed_con      = "Сиз суҳбатни ёпдингиз!"
        waiting         = "Ҳозирча сиз кутиш рўйхатидасиз. Aдмин сизга тез орада жавоб беради!"
        fix_that        = "Ички сервер хатоси!"
        mes_update      = "Сизнинг хабарингиз қўшилди. Яна хабарлар жўнатишингиз мумкин."
        should_choose   = "Сиз суҳбат қилиш учун фойдаланувчини танлашингиз керак."
        internal        = "Ички хато суҳбат топилмади!"
        choose_new      = "Ушбу фойдаланувчи кутиш рўйхатида эмас! Илтимос бошқа фойдаланувчини танланг."
        user            = "Фойдаланувчи: "
        user_id         = "ID: "
        date            = "Сана: "
        con_start_err   = "Суҳбат бошлашда хатолик. Бошқа фойдаланувчи танланг."
        error           = "Хатолик!"
        chosen          = "Фойдаланувчи танланди!"
        had_con         = "Aдмин фойдаланувчи билан суҳбақ қилаётган эди - "
        send_wait       = "Фойдаланувчи кутиш рўйхатига ўтказилади!"
        cant_del_con    = "Ўчирилаётган Aдминнинг суҳбатини ўчиришда хатолик!"
        con_del         = "Aдмин суҳбати ўчирилди!"
        prev_admin      = "Олдинги админ суҳбат жараёнида ўчирилган!"
        was_deleted     = "Узур суҳбат админи ўчирилди. Енди сиз кутиш рўйхатига ўтказилдингиз."
        con_lost        = "Фойдаланувчини кутиш рўйхатига ўтказишда хатолик! Суҳбат йўқотилди!"
        cant_del_adm    = "Aдминни ўчиришда хатолик, Aдминлар рўйхатини текширинг!"
        adm_del         = "Aдмин ўчирилди!"
        done            = "Бажарилди!"
        close_con       = "✖️Чатни ёпиш✖️"
        ch_lang         = "🇬🇧Тилни алмаштириш🇷🇺"
        choose_lan      = "Тилни танланг: "
        same_lang       = "Бу сизнинг тилингиз!"
        chooseUser      = "👥Фойдаланувчилар👥"
        allAdmins       = "👥Админлар👥"
        closeCon        = "✖️Чатни ёпиш✖️"
        exit            = "🚪Админдан чиқиш🚪"
        user_closed     = "Фойдаланувчи бу чатни ёпди!"
        admin_closed    = "Админ бу чатни ёпди!"
        please_rate     = "Илтимос, операторга 1 дан 5 гача баҳо беринг"
        thanks          = "Раҳмат!"
        tell_report     = "Балингиз сабабини бизга айта оласизми?"
        tell_no         = "🙅‍♂️Йўқ, истамайман🙅‍♂️"
        feedback        = "🙏Мулоҳазаларингиз учун раҳмат!🙏"
        super_admin     = "Сиз ушбу ботнинг эгасига айландингиз."
        delAdmin        = "🗑Aдмини ўчириш🗑"
        chats           = "Чатлар: "
        rate            = "Баҳо: "
        spr             = "Бот эгаси: "
        thisisyou       = "Бу сиз!"
        admin_del_you   = "Бот эгаси сизни админдан ўчирди!"
        hanging_user    = "Битта фойдаланувчи жавоб кутмоқда"
        hanging_many    = "%s та фойдаланувчилар жавоб кутишмоқда!"
        lang            = "Тил: "

    def gl(self, lan_str:str) -> en:
        if lan_str == "en":
            return self.en
        elif lan_str == "ru":
            return self.ru
        elif lan_str == "uz":
            return self.uz
        elif lan_str == "oz":
            return self.oz
        return self.en

    def gal(self, field:str):
        return [
            self.en.__getattribute__(self.en, field),
            self.ru.__getattribute__(self.ru, field),
            self.uz.__getattribute__(self.uz, field),
            self.oz.__getattribute__(self.oz, field)
        ]
lang = Lang()